version: "3.5"
services:
  flaskr:
    image: dockerhub.datagrand.com/smfg/smfg_api:release_202111141446
    container_name: flaskr
    restart: always
    environment:
      ENV: "default"
    #      ENVIRONMENT: "default"
    #      REDIS_HOST: "100.100.20.144"
    #      REDIS_PORT: 63791
    #      REDIS_DB: 1
    ports:
      - "8000:8000"
    volumes:
      - ../flask_app:/flask_app
      - ./log:/logs
    deploy:
      replicas: 2



#  flaskr_celery:
#    image: flaskr:release_20210809101523
#    container_name: flaskr_celery
#    command: celery -A celery_task.celery_process.celery_app worker -l info
#    environment:
#      ENV: "test"
#      ENVIRONMENT: "default"
#      REDIS_HOST: "100.100.20.144"
#      REDIS_PORT: 63791
#      REDIS_DB: 1
#    volumes:
#      - ../../app:/flaskr/app

#
#  redis:
#    image: redis
#    container_name: redis
#    command: redis-server --requirepass 123456
#    restart: always
#    volumes:
#      - ../data/redis/db:/data
#    ports:
#      - 63791:6379
#
#  mysql:
#    image: mysql
#    container_name: mysql
#    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
#    environment:
#      #            - MYSQL_ROOT_PASSWORD=shang.666
#      #            - MYSQL_USER=root
#      - MYSQL_PASSWORD=shang.666
#    restart: always
#    volumes:
#      - ../data/mysql/db:/var/lib/mysql
#      - ../data/mysql/conf/my.cnf:/etc/my.cnf
#      - ../data/mysql/init:/docker-entrypoint-initdb.d/
#    ports:
#      - 33061:3306
#
#  rabbitmq:
#    image: rabbitmq:3.7-management
#    container_name: rabbitmq
#    environment:
#      - RABBITMQ_DEFAULT_USER=admin   # 用户名
#      - RABBITMQ_DEFAULT_PASS=admin   # 密码
#      #            - RABBITMQ_DEFAULT_VHOST=my_vhost
#    restart: always
#    volumes:
#      - ./data/rabitmq:/var/lib/rabbitmq
#      - /etc/localtime:/etc/localtime
#    ports:
#      - 5672:5672 #集群内部访问的端口
#      - 15672:15672 #外部访问的端口