version: "3.5"
services:
    flaskr:
        image: flaskr:latest
        container_name: flaskr
        depends_on:
          - mysql
          - redis
        volumes:
            - ../data/flaskr/logs:/flaskr/logs
            - ../deploy/default:/etc/nginx/sites-available/default
        ports:
            - 8088:80

    redis:
        image: redis
        container_name: redis
        # command: --appendonly yes
        command: redis-server --requirepass 123456
        restart: always
        volumes:
            - ../data/redis/db:/data
        ports:
            - 63791:6379

    mysql:
        image: mysql
        container_name: mysql
        command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
        environment:
            - MYSQL_ROOT_PASSWORD=shang.666
            - MYSQL_USER=root
            - MYSQL_PASSWORD=shang.666
        restart: always
        volumes:
            - ../data/mysql/db:/var/lib/mysql
            - ../data/mysql/conf/my.cnf:/etc/my.cnf
            - ../data/mysql/init:/docker-entrypoint-initdb.d/
        ports:
            - 33061:3306

    rabbitmq:
        image: rabbitmq
        container_name: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=admin   # 用户名
            - RABBITMQ_DEFAULT_PASS=admin   # 密码
            #            - RABBITMQ_DEFAULT_VHOST=my_vhost
        restart: always
        volumes:
            - ../data/rabitmq:/var/lib/rabbitmq
        ports:
            - 5672:5672 #集群内部访问的端口
            - 15672:15672 #外部访问的端口
